#!/usr/bin/env bash
# Install/setup script for My Free Farm Bash Bot on macOS
# Uses Homebrew for dependencies and a self-contained lighttpd config.
#
# Unlike the Linux/Cygwin installers this script does NOT download the bot
# (you already have the repository) and does NOT move the GUI to /var/www.
# Instead it serves the GUI straight out of this repository and runs lighttpd
# as your own user on a non-privileged port, so no sudo is required.
#
# Run it from the bot directory, which MUST be ~/mffbashbot:
#   cd ~/mffbashbot && ./install-macos.sh

set -e

# --- sanity checks ---------------------------------------------------------
if ! uname -a | grep -qi "darwin"; then
 echo "This installer is for macOS only. Use install.sh (Linux) or install-cygwin.sh (Windows)."
 exit 1
fi

SCRIPTDIR="$(cd "$(dirname "$0")" && pwd)"
GUIROOT="$SCRIPTDIR/mffbashbot-GUI"
LCONF="$SCRIPTDIR/lighttpd-macos.conf"

if [ ! -d "$GUIROOT" ]; then
 echo "Could not find mffbashbot-GUI next to this script. Run it from inside the bot directory."
 exit 1
fi

# The GUI hard-codes 'cd ~/mffbashbot' in the generated start scripts, so the
# bot really has to live there.
if [ "$SCRIPTDIR" != "$HOME/mffbashbot" ]; then
 echo "WARNING: this directory is '$SCRIPTDIR', but the bot must live in '$HOME/mffbashbot'."
 echo "Please move it there first, e.g.:  mv \"$SCRIPTDIR\" \"$HOME/mffbashbot\""
 exit 1
fi

# --- Homebrew + dependencies ----------------------------------------------
if ! command -v brew &>/dev/null; then
 echo "Homebrew is required but was not found. Install it from https://brew.sh and re-run."
 exit 1
fi
BREW="$(brew --prefix)"

MISSING=()
# bash >= 4.3 (macOS ships 3.2, so we need the Homebrew one)
if [ "$(bash -c 'echo ${BASH_VERSINFO[0]}')" -lt 4 ]; then
 MISSING+=(bash)
fi
command -v php-cgi &>/dev/null || MISSING+=(php)
command -v wget    &>/dev/null || MISSING+=(wget)
command -v jq      &>/dev/null || MISSING+=(jq)
command -v screen  &>/dev/null || MISSING+=(screen)
if ! command -v lighttpd &>/dev/null && [ ! -x "$BREW/sbin/lighttpd" ]; then
 MISSING+=(lighttpd)
fi

if [ ${#MISSING[@]} -ne 0 ]; then
 echo "Missing dependencies. Please install them and re-run this script:"
 echo
 echo "    brew install ${MISSING[*]}"
 echo
 echo "If 'bash' is among them, also make sure the Homebrew bash comes first in"
 echo "your PATH (e.g. add '$BREW/bin' to the front of PATH in ~/.zprofile)."
 exit 1
fi

LIGHTTPD="$(command -v lighttpd || echo "$BREW/sbin/lighttpd")"
PHPCGI="$(command -v php-cgi)"

echo "All dependencies found."
echo "  bash:     $(command -v bash) ($(bash -c 'echo $BASH_VERSION'))"
echo "  php-cgi:  $PHPCGI"
echo "  lighttpd: $LIGHTTPD"
echo

# --- permissions -----------------------------------------------------------
echo "Setting permissions..."
chmod +x "$SCRIPTDIR"/*.sh
chmod +x "$GUIROOT"/script/*.sh

# --- patch GUI config.php for the macOS home layout ------------------------
# On Linux/Cygwin the base is /home/<user>/; on macOS it is /Users/<user>/.
echo "Patching GUI config.php..."
sed -i.bak 's#/home/pi/mffbashbot/#'"$HOME"'/mffbashbot/#' "$GUIROOT/config.php" && rm -f "$GUIROOT/config.php.bak"

# --- write a self-contained lighttpd config --------------------------------
echo "Writing lighttpd config to $LCONF..."
cat > "$LCONF" <<EOF
# Auto-generated by install-macos.sh for My Free Farm Bash Bot
server.document-root        = "$GUIROOT"
server.port                 = 8080
server.modules              = ( "mod_setenv", "mod_cgi" )
server.errorlog             = "$SCRIPTDIR/lighttpd-error.log"
# ensure the CGI scripts find the Homebrew tools (wget, jq, bash, ...);
# lighttpd/php-cgi otherwise runs with a minimal PATH that lacks the brew bins
setenv.add-environment      = ( "PATH" => "$BREW/bin:$BREW/sbin:/usr/bin:/bin:/usr/sbin:/sbin" )
index-file.names            = ( "index.php" )
mimetype.assign             = (
  ".html" => "text/html",
  ".css"  => "text/css",
  ".js"   => "application/javascript",
  ".png"  => "image/png",
  ".jpg"  => "image/jpeg",
  ".jpeg" => "image/jpeg",
  ".gif"  => "image/gif",
  ".svg"  => "image/svg+xml",
  ".ico"  => "image/x-icon"
)
cgi.assign                  = ( ".php" => "$PHPCGI" )
# needed so the live bot output (Server-Sent Events) is streamed, not buffered
server.stream-response-body = 1
EOF

# --- .screenrc (nicer screen status line) ----------------------------------
if [ ! -f ~/.screenrc ]; then
 echo "Creating ~/.screenrc..."
 cat > ~/.screenrc <<'EOF'
hardstatus alwayslastline
hardstatus string "%{.bW}%-w%{.rW}%n %t%{-}%+w %=%{..G} %H %{..Y}"
defscrollback 5000
EOF
fi

# --- initial start script --------------------------------------------------
# The GUI regenerates ~/startallbots.sh whenever farms are added/removed; this
# initial version just brings up the web GUI so you can add your first farm.
echo "Creating initial start script ~/startallbots.sh..."
cat > "$HOME/startallbots.sh" <<EOF
#!/usr/bin/env bash
pkill -x lighttpd 2>/dev/null; sleep 1
$LIGHTTPD -f $LCONF
EOF
chmod +x "$HOME/startallbots.sh"

echo
echo "Done!"
echo
echo "1) Start the web GUI:      ~/startallbots.sh"
echo "2) Open in your browser:   http://localhost:8080"
echo "3) Add your farm there. After adding a farm, ~/startallbots.sh is"
echo "   regenerated to also launch the bot in a 'screen' session."
echo "4) To watch the bot:       screen -r mffbashbot   (detach with Ctrl-A then D)"
echo
echo "To stop lighttpd later:    pkill lighttpd"
